apiVersion: apps/v1
kind: Deployment
metadata:
  name: niloy-app-master-deployment
  namespace: kubernetes-cluster-niloybiswas
  labels:
    app: niloy-app-master
spec:
  replicas: 4
  selector:
    matchLabels:
      app: niloy-app-master
  template:
    metadata:
      labels:
        app: niloy-app-master
    spec:
      containers:
        - name: niloy-app-master
          image: dreamspace04/master:latest
          ports:
            - name: http
              containerPort: 7100
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: kubernetes-cluster-niloybiswas
spec:
  selector:
    app: niloy-app-master
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30157
      targetPort: 7100
      port: 7100
