kind: Namespace
apiVersion: v1
metadata:
  name: kubernetes-cluster-niloybiswas
  labels: 
    name: kubernetes-cluster-niloybiswas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kubernetes-cluster-niloybiswas
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: dreamspace04/nagp-devops-nodejs:16
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits: 
              memory: "400Mi"
              cpu: "500m"   

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: kubernetes-cluster-niloybiswas
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9600
      targetPort: 3001